/* automatically generated by rust-bindgen */

pub const pqcrystals_kyber1024_ref_SECRETKEYBYTES: u32 = 3168;
pub const pqcrystals_kyber1024_ref_PUBLICKEYBYTES: u32 = 1568;
pub const pqcrystals_kyber1024_ref_CIPHERTEXTBYTES: u32 = 1568;
pub const pqcrystals_kyber1024_ref_BYTES: u32 = 32;
pub type __uint8_t = ::std::os::raw::c_uchar;
extern "C" {
    pub fn pqcrystals_kyber1024_ref_keypair(pk: *mut u8, sk: *mut u8) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn pqcrystals_kyber1024_ref_enc(
        ct: *mut u8,
        ss: *mut u8,
        pk: *const u8,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn pqcrystals_kyber1024_ref_dec(
        ss: *mut u8,
        ct: *const u8,
        sk: *const u8,
    ) -> ::std::os::raw::c_int;
}
